name: "Setup Markdown to PDF tooling"
description: "Setup Markdown to PDF tooling"
inputs:
  texlive-distribution:
    description: Year of TeX Live distribution
    default: "2023"
    required: false
  pandoc-version:
    description: Pandoc version to install (https://github.com/jgm/pandoc/releases)
    default: "2.11.3.2"
    required: false
  crossref-version:
    description: Pandoc cross ref version (needs to match pandoc-version) (https://github.com/lierdakil/pandoc-crossref/releases)
    default: "0.3.9.0a"
    required: false
runs:
  using: composite
  steps:
    - name: Install TinyTeX
      uses: r-lib/actions/setup-tinytex@v2
      env:
        TINYTEX_INSTALLER: TinyTeX-1
    - run: echo $PATH
      shell: bash
    - run: ls /c/Users/runneradmin/AppData/Roaming/TinyTeX/bin/windows
      if: runner.os != 'Windows'
      shell: bash
    - run: tlmgr --version
      shell: bash
#    - name: Set TeX Live repository
#      run: tlmgr option repository ftp://ftp.math.utah.edu/pub/tex/historic/systems/texlive/${{ inputs.texlive-distribution }}/tlnet-final
#      shell: bash
    - name: Update tlmgr
      run: tlmgr update --self
      shell: bash
    - name: Add tlmgr to path
      run: tlmgr path add
      shell: bash
    - name: Install Pandoc
      uses: r-lib/actions/setup-pandoc@v2
      with:
        pandoc-version: ${{ inputs.pandoc-version }}
    - name: Install Pandoc crossref (Windows)
      if: runner.os == 'Windows'
      run: |
        curl.exe -L --output pandoc-crossref.7z --url https://github.com/lierdakil/pandoc-crossref/releases/download/v${{ inputs.crossref-version }}/pandoc-crossref-${{ runner.os }}.7z
        "C:\Program Files\7-Zip\7z.exe" x pandoc-crossref.7z
      shell: bash
    - name: Install Pandoc crossref (Non-windows)
      if: runner.os != 'Windows'
      run: |
        curl -L --output pandoc-crossref.tar.xz --url https://github.com/lierdakil/pandoc-crossref/releases/download/v${{ inputs.crossref-version }}/pandoc-crossref-${{ runner.os }}.tar.xz
        tar -xf pandoc-crossref.tar.xz
      shell: bash
