name: "Setup Python and Poetry"
description: "Setup Python Environment Using Poetry"
inputs:
  python-version:
    description: Python version used to create the environment
    required: true
  pyproject-directory:
    description: Directory containing pyproject.toml
    default: "."
    required: false
runs:
  using: composite
  steps:
    - name: Setup python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install Poetry
      run: pipx install poetry==1.7.1
      shell: bash
    - name: Install dependencies #if cache does not exist
      run: poetry install
      working-directory: ${{ inputs.pyproject-directory }}
      shell: bash
